copleted validations
learn-academy-2023-foxtrot/cat-tinder-backend-district-12 pull request #4
Opened 2023-10-17 22:51 UTC by XenaSit

2023-10-17 23:09 UTC, SunkissedQueen commented on spec/models/tribute_spec.rb
> +  it 'should return length of hobby' do
Did you mean 'validate'?

2023-10-17 23:11 UTC, XenaSit commented on spec/models/tribute_spec.rb
> +  it 'should return length of hobby' do
yes

2023-10-17 23:25 UTC, SunkissedQueen requested changes
Hey team. During lectures, I might not be able to complete all the tasks. However, the goal is for your team to perform all the MVP tasks as outlined on the Trello.
Please complete the Requests checklist on the Trello card. Ping me on the same thread for your PR when the changes have been made.

2023-10-17 23:25 UTC, SunkissedQueen commented on spec/models/tribute_spec.rb
> +  it 'should return image' do
Did you mean 'validate'?

2023-10-17 23:25 UTC, SunkissedQueen commented on spec/models/tribute_spec.rb
> +  it 'should return district' do
Did you mean 'validate'?

2023-10-18 03:18 UTC, SunkissedQueen approved these changes

2023-10-18 15:52 UTC, merged